version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgres://dockeruser:dockerpassword@postgres:5432/dockerdb
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  postgres-data:
